### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by gteufelberger** [aris-space/helios-data-analysis#1]
Some first few things to do

- [x] Format Python code with `black` -> 2e2df5f6a3761f6eae20815909bcfacfd1f224b2
- [x] Decouple all reliance on old MCPC -> #6 #7
- [x] Add some way of storing server credentials that avoids accidentally committing them -> #3
- [ ] ???
